// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9ZTxcrXUrwydO3p3zBT-qN4LpstuvKY',
    appId: '1:416882440619:web:fcd90a62e223bef936faee',
    messagingSenderId: '416882440619',
    projectId: 'foodshare-cc295',
    authDomain: 'foodshare-cc295.firebaseapp.com',
    storageBucket: 'foodshare-cc295.appspot.com',
    measurementId: 'G-7NSJE6H83W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmdNJ3Q-bovGeLP_wzLdsVZrv-7Jjjb4E',
    appId: '1:416882440619:android:d5350c279aa6121536faee',
    messagingSenderId: '416882440619',
    projectId: 'foodshare-cc295',
    storageBucket: 'foodshare-cc295.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM-zWXp-XC4cxv8uv3GKbrj_nshELm8zA',
    appId: '1:416882440619:ios:21640f8d543091df36faee',
    messagingSenderId: '416882440619',
    projectId: 'foodshare-cc295',
    storageBucket: 'foodshare-cc295.appspot.com',
    iosClientId: '416882440619-9iffhlbvdsdof2gce9l0a1lo4kn6d25e.apps.googleusercontent.com',
    iosBundleId: 'com.zero.foodshare',
  );
}
